# Generated by Django 5.0 on 2023-12-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('eye_color', models.CharField(max_length=255)),
                ('hair_color', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('eye_colors', models.CharField(max_length=255)),
                ('hair_colors', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('climate', models.CharField(max_length=255)),
                ('terrain', models.CharField(max_length=255)),
                ('surface_water', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('residents', models.ManyToManyField(related_name='locations', to='main.person')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.species'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('vehicle_class', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('length', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='main.person')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('original_title_romanised', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('movie_banner', models.URLField()),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('release_date', models.CharField(max_length=4)),
                ('running_time', models.CharField(max_length=10)),
                ('rt_score', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('locations', models.ManyToManyField(to='main.location')),
                ('people', models.ManyToManyField(to='main.person')),
                ('species', models.ManyToManyField(to='main.species')),
                ('vehicles', models.ManyToManyField(to='main.vehicle')),
            ],
        ),
    ]
